# PASSWORD: 5f5517e3cf9e40ada186f5f040191ba8

services:
  jenkins:
    # image: jenkins/jenkins:lts-jdk17
    build:
      context: .
      dockerfile: Dockefile.jenkins
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
